import fs from "node:fs";
import path from "node:path";

/**
 * Review analysis, Claude-generated themes + sentiment + pull quote,
 * cached to disk at content/review-analysis/{slug}.json.
 *
 * Generated by `scripts/analyze-reviews.ts` (run manually, one-off).
 * The display (components/insights/ReviewVoice.tsx) prefers this when it
 * exists and falls back to regex-mined phrases otherwise.
 */

export type ReviewTheme = {
  /** Short phrase, 2-5 words. */
  phrase: string;
  /** Approximate count across the reviews. */
  frequency: number;
  /** Sentiment polarity of the theme. */
  sentiment: "positive" | "neutral" | "negative";
  /** Optional one-sentence quote from a review that illustrates this theme. */
  exampleQuote?: string;
};

export type AnalysisPlaybookItem = {
  headline: string;
  action: string;
  signal:
    | "momentum"
    | "content_canvas"
    | "community_spark"
    | "conversion_path"
    | "collab_fit";
  priority: "high" | "medium" | "low";
};

export type ReviewAnalysis = {
  slug: string;
  themes: ReviewTheme[];
  /** One-sentence summary of what reviewers love + what they nitpick. */
  sentiment_summary: string;
  /** One quote that captures the business's appeal. */
  notable_quote: string;
  /** How many reviews were analyzed. */
  review_count: number;
  /** When the analysis was generated. */
  analyzed_at: string;
  /** Model name used. */
  model: string;

  // Enriched fields from scripts/analyze-business.ts (optional for back-compat
  // with earlier analyses generated by scripts/analyze-reviews.ts).
  /** 2-3 sentence editorial paragraph for this business's quarter. */
  quarter_narrative?: string;
  /** One-sentence diagnosis, the "read" for the TL;DR block. */
  tldr_read?: string;
  /** One-sentence trajectory description, the "meaning" for TL;DR. */
  tldr_meaning?: string;
  /** Three data-derived recommendations, sorted by priority. */
  playbook?: AnalysisPlaybookItem[];
};

const ANALYSIS_DIR = path.join(process.cwd(), "content", "review-analysis");

export function loadReviewAnalysis(slug: string): ReviewAnalysis | null {
  const filePath = path.join(ANALYSIS_DIR, `${slug}.json`);
  if (!fs.existsSync(filePath)) return null;
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as ReviewAnalysis;
  } catch {
    return null;
  }
}
