import { notFound } from "next/navigation";
import Link from "next/link";

import { Masthead } from "@/components/Masthead";
import { Colophon } from "@/components/Colophon";
import { Reveal } from "@/components/motion/Reveal";
import { SubscribeFooter } from "@/components/SubscribeFooter";
import {
  isPostArticle,
  listAllListSlugs,
  loadListArticleBySlug,
  type ListArticleItem,
  type PostArticleItem,
} from "@/lib/data/load-list";
import { TikTokEmbedPreview } from "@/components/insights/TikTokEmbedPreview";
import { InstagramEmbedPreview } from "@/components/insights/InstagramEmbedPreview";

/**
 * /best-on-social/[slug], the renderer for ranked-list articles
 * generated by `npm run generate:lists`.
 *
 * Layout: magazine-style. Masthead, big editorial hero with title +
 * Claude-generated intro paragraphs, then a stack of ranked cards with
 * rank, name, descriptor, stat line, featured TikTok creator pull, and
 * a "read the record" link to the full business page.
 *
 * Articles are pre-rendered statically. Re-run the generator and
 * redeploy to refresh.
 */

type PageProps = {
  params: Promise<{ slug: string }>;
};

export function generateStaticParams(): { slug: string }[] {
  return listAllListSlugs().map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: PageProps) {
  const { slug } = await params;
  const article = loadListArticleBySlug(slug);
  if (!article) return { title: "Not found, Signal Pittsburgh" };
  return {
    title: `${article.title}, Signal Pittsburgh`,
    description: article.angle,
  };
}

function formatPlays(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M plays`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}K plays`;
  return `${n.toLocaleString()} plays`;
}

function splitDescriptor(line: string, highlight: string): {
  before: string;
  match: string;
  after: string;
} | null {
  if (!highlight) return null;
  const idx = line.toLowerCase().indexOf(highlight.toLowerCase());
  if (idx === -1) return null;
  return {
    before: line.slice(0, idx),
    match: line.slice(idx, idx + highlight.length),
    after: line.slice(idx + highlight.length),
  };
}

function PostItemCard({ item }: { item: PostArticleItem }) {
  const date = item.posted ? new Date(item.posted) : null;
  const dateLabel = date
    ? date.toLocaleDateString("en-US", { month: "short", day: "numeric" })
    : "";
  return (
    <Reveal as="article" className="block">
      <div className="grid grid-cols-[3rem_1fr] md:grid-cols-[5rem_1fr] gap-4 md:gap-6 border-b border-brand-black/15 pb-8 md:pb-10">
        <div>
          <span className="font-display text-3xl md:text-5xl font-black tabular-nums tracking-[-0.02em] text-brand-purple">
            {String(item.rank).padStart(2, "0")}
          </span>
        </div>
        <div className="min-w-0 grid grid-cols-1 md:grid-cols-[1fr_auto] gap-5 md:gap-7 items-start">
          <div className="min-w-0">
            <p className="font-display text-[0.62rem] font-semibold uppercase tracking-[0.18em] text-brand-black/55">
              {item.neighborhood}
            </p>

            <h3 className="mt-2 font-display font-black uppercase tracking-[-0.01em] text-brand-black text-xl md:text-2xl leading-[1.1]">
              <Link
                href={`/business/${item.business_slug}`}
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-brand-purple transition-colors"
              >
                {item.business_name}
              </Link>
            </h3>

            <p className="mt-1 font-body text-xs text-brand-black/55">
              <a
                href={item.video_url}
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-brand-purple"
              >
                @{item.creator_handle}
              </a>
            </p>

            {/* Creativity score badge + editorial "why" line, only on
                the most-creative list where these fields exist. */}
            {item.creativity_score !== undefined &&
              Number.isFinite(item.creativity_score) && (
              <div className="mt-4 flex flex-col gap-2">
                <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                  <span className="inline-flex items-center bg-brand-lime text-brand-black font-display text-[0.62rem] font-semibold uppercase tracking-[0.18em] px-2 py-0.5">
                    Creativity {item.creativity_score.toFixed(1)} / 10
                  </span>
                  {item.scores ? (
                    <span className="font-body text-[0.7rem] text-brand-black/55">
                      Visual {item.scores.visual_concept} · Caption{" "}
                      {item.scores.caption_craft} · Format{" "}
                      {item.scores.format_fit} · Surprise{" "}
                      {item.scores.surprise}
                    </span>
                  ) : null}
                </div>
                {item.why ? (
                  <p className="font-body text-xs md:text-sm text-brand-black/75 italic leading-snug border-l-2 border-brand-purple pl-3">
                    {item.why}
                  </p>
                ) : null}
              </div>
            )}

            <div className="mt-4 flex flex-wrap items-baseline gap-x-4 gap-y-1">
              {item.platform === "instagram" ? (
                <span className="font-display text-base md:text-lg font-black tabular-nums text-brand-black">
                  {item.likes.toLocaleString()}{" "}
                  <span className="font-body font-normal text-xs uppercase tracking-[0.14em] text-brand-black/55">
                    likes
                  </span>
                </span>
              ) : (
                <span className="font-display text-base md:text-lg font-black tabular-nums text-brand-black">
                  {item.plays.toLocaleString()}{" "}
                  <span className="font-body font-normal text-xs uppercase tracking-[0.14em] text-brand-black/55">
                    plays
                  </span>
                </span>
              )}
              {item.platform === "instagram" && item.plays > 0 ? (
                <span className="font-body text-xs text-brand-black/55 tabular-nums">
                  {item.plays.toLocaleString()} plays
                </span>
              ) : null}
              {item.platform !== "instagram" && item.likes > 0 ? (
                <span className="font-body text-xs text-brand-black/55 tabular-nums">
                  {item.likes.toLocaleString()} likes
                </span>
              ) : null}
              {item.comments && item.comments > 0 ? (
                <span className="font-body text-xs text-brand-black/55 tabular-nums">
                  {item.comments.toLocaleString()} comments
                </span>
              ) : null}
              {dateLabel ? (
                <span className="font-body text-xs text-brand-black/60">
                  Posted {dateLabel}
                </span>
              ) : null}
            </div>

            <div className="mt-4">
              <a
                href={item.video_url}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1 font-display text-[0.7rem] font-semibold uppercase tracking-[0.18em] text-brand-purple hover:text-brand-black transition-colors"
              >
                {item.platform === "instagram"
                  ? "View on Instagram"
                  : "Watch on TikTok"}
                <span aria-hidden="true">↗</span>
              </a>
            </div>
          </div>
          <div className="md:order-last w-40 sm:w-48 md:w-[200px] shrink-0">
            {item.platform === "instagram" ? (
              <InstagramEmbedPreview
                postUrl={item.video_url}
                shortcode={item.video_id}
                thumbnailUrl={item.thumbnail_url}
                caption={item.caption}
              />
            ) : (
              <TikTokEmbedPreview
                videoUrl={item.video_url}
                videoId={item.video_id}
                thumbnailUrl={item.thumbnail_url}
                caption={item.caption}
              />
            )}
          </div>
        </div>
      </div>
    </Reveal>
  );
}

function ItemCard({ item }: { item: ListArticleItem }) {
  const split = splitDescriptor(item.descriptor, item.descriptor_highlight);
  return (
    <Reveal as="article" className="block">
      <div className="grid grid-cols-[3rem_1fr] md:grid-cols-[5rem_1fr] gap-4 md:gap-6 border-b border-brand-black/15 pb-8 md:pb-10">
        {/* Rank */}
        <div>
          <span className="font-display text-3xl md:text-5xl font-black tabular-nums tracking-[-0.02em] text-brand-purple">
            {String(item.rank).padStart(2, "0")}
          </span>
        </div>

        {/* Body */}
        <div className="min-w-0">
          <Link
            href={`/business/${item.business_slug}`}
            className="group inline-block"
          >
            <h3 className="font-display font-black uppercase tracking-[-0.02em] text-brand-black text-2xl md:text-4xl leading-[1] [text-wrap:balance] group-hover:text-brand-purple transition-colors">
              {item.name}
            </h3>
          </Link>
          <p className="mt-2 font-body text-xs md:text-sm text-brand-black/55 uppercase tracking-[0.14em]">
            {item.neighborhood} · {item.family_label}
          </p>

          {/* Descriptor (the rank-grounded diagnosis line) */}
          <h4 className="mt-5 font-display font-black uppercase tracking-[-0.01em] text-brand-black text-lg md:text-2xl leading-[1.05] [text-wrap:balance]">
            {split ? (
              <>
                {split.before}
                <span className="bg-brand-lime text-brand-black px-1.5 box-decoration-clone">
                  {split.match}
                </span>
                {split.after}
              </>
            ) : (
              item.descriptor
            )}
          </h4>

          {/* Stat line */}
          <p className="mt-4 font-body text-sm md:text-base text-brand-black/80 leading-relaxed">
            {item.stat_line}
          </p>

          {/* Featured TikTok */}
          {item.featured_tiktok ? (
            <div className="mt-5 inline-flex items-baseline flex-wrap gap-x-3 gap-y-1 border-l-2 border-brand-purple pl-4 py-1">
              <span className="font-display text-[0.6rem] font-semibold uppercase tracking-[0.18em] text-brand-purple">
                Top creator pull
              </span>
              <a
                href={item.featured_tiktok.url}
                target="_blank"
                rel="noopener noreferrer"
                className="font-display text-sm md:text-base font-semibold text-brand-black hover:text-brand-purple transition-colors"
              >
                @{item.featured_tiktok.author}
              </a>
              <span className="font-body text-xs md:text-sm text-brand-black/65 tabular-nums">
                {formatPlays(item.featured_tiktok.plays)}
              </span>
            </div>
          ) : null}

          <Link
            href={`/business/${item.business_slug}`}
            className="mt-5 inline-flex items-center gap-1 font-display text-[0.7rem] font-semibold uppercase tracking-[0.18em] text-brand-black hover:text-brand-purple transition-colors"
          >
            Read the record
            <span aria-hidden="true">→</span>
          </Link>
        </div>
      </div>
    </Reveal>
  );
}

export default async function BestOnSocialArticlePage({ params }: PageProps) {
  const { slug } = await params;
  const article = loadListArticleBySlug(slug);
  if (!article) notFound();

  const introParagraphs = article.intro
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <>
      <Masthead variant="compact" />

      <main className="flex-1">
        <article className="mx-auto max-w-3xl px-6 py-10 md:py-14">
          {/* Breadcrumb */}
          <nav
            aria-label="Breadcrumb"
            className="font-body text-xs md:text-sm text-brand-black/60"
          >
            <ol className="flex flex-wrap items-center gap-1.5">
              <li>
                <Link href="/" className="hover:text-brand-purple">
                  Pittsburgh
                </Link>
              </li>
              <li aria-hidden="true">›</li>
              <li>
                <Link
                  href="/best-on-social"
                  className="hover:text-brand-purple"
                >
                  Best on Social
                </Link>
              </li>
              <li aria-hidden="true">›</li>
              <li>
                <span>{article.title}</span>
              </li>
            </ol>
          </nav>

          {/* Hero */}
          <header className="mt-6 md:mt-8">
            <p className="font-display text-[0.62rem] font-semibold uppercase tracking-[0.22em] text-brand-purple">
              The Series · Spring 2026
            </p>
            <h1 className="mt-3 font-display font-black uppercase tracking-[-0.02em] text-brand-black text-[clamp(2rem,6vw,4.25rem)] leading-[0.95] [text-wrap:balance]">
              {article.title}
            </h1>
            {article.subtitle ? (
              <p className="mt-4 font-body text-base md:text-lg text-brand-black/70 [text-wrap:balance]">
                {article.subtitle}
              </p>
            ) : null}
          </header>

          {/* Intro paragraphs */}
          <Reveal as="div" className="block">
            <div className="mt-8 md:mt-10 space-y-4 md:space-y-5">
              {introParagraphs.map((p, i) => (
                <p
                  key={i}
                  className={
                    i === 0
                      ? "font-body text-lg md:text-xl text-brand-black leading-relaxed first-letter:font-display first-letter:text-5xl md:first-letter:text-6xl first-letter:font-black first-letter:float-left first-letter:mr-2 first-letter:leading-[0.85] first-letter:text-brand-purple"
                      : "font-body text-base md:text-lg text-brand-black/85 leading-relaxed"
                  }
                >
                  {p}
                </p>
              ))}
            </div>
          </Reveal>

          {/* The list, branches on article kind, business cards or post cards */}
          <section className="mt-12 md:mt-16">
            <div className="border-y-2 border-brand-black py-3 mb-8 md:mb-10 flex flex-wrap items-baseline justify-between gap-3">
              <h2 className="font-display text-xs font-semibold uppercase tracking-[0.2em] text-brand-black">
                The list
              </h2>
              <span className="font-body text-xs text-brand-black/55 uppercase tracking-[0.14em]">
                {article.items.length}{" "}
                {isPostArticle(article)
                  ? article.items.length === 1
                    ? "post"
                    : "posts"
                  : article.items.length === 1
                    ? "business"
                    : "businesses"}
                {article.query
                  ? ` · ranked by ${String(article.query.ranking).replace(/_/g, " ")}`
                  : isPostArticle(article)
                    ? " · ranked by plays"
                    : ""}
              </span>
            </div>
            <div className="space-y-8 md:space-y-10">
              {isPostArticle(article)
                ? article.items.map((item) => (
                    <PostItemCard
                      key={`${item.creator_handle}-${item.video_url}`}
                      item={item}
                    />
                  ))
                : (article.items as ListArticleItem[]).map((item) => (
                    <ItemCard key={item.business_slug} item={item} />
                  ))}
            </div>
          </section>

          {/* Subscribe footer */}
          <div className="mt-16 md:mt-20">
            <SubscribeFooter businessName="this list" />
          </div>
        </article>
      </main>

      <Colophon />
    </>
  );
}
